# Generated by Django 4.2.2 on 2023-10-07 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3, max_length=255)),
                ('monthlyincome', models.DecimalField(decimal_places=1, max_digits=3, max_length=255)),
            ],
        ),
    ]
