# Generated by Django 4.1.7 on 2023-10-09 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SatatementChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('age', models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlyincome', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('rent_expense', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('current_balance', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('food_expense', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('transportation_expense', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('utilities_expense', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('miscellaneous_expense', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('disposable_income', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('current_debt', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('time_to_pay', models.DecimalField(decimal_places=1, max_digits=10, max_length=255, null=True)),
                ('risk_tolerance', models.CharField(max_length=255)),
                ('current_goal', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='account.user')),
            ],
        ),
    ]
