# Generated by Django 4.2.2 on 2023-10-07 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
    ]
