# Generated by Django 4.2.2 on 2023-10-08 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_monthlyincome'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthlyincome', models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True)),
                ('rent_expense', models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True)),
                ('food_expense', models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True)),
                ('transportation_expense', models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True)),
                ('utilities_expense', models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True)),
            ],
        ),
    ]
