# Generated by Django 4.2.2 on 2023-10-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_financialstatement'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='miscellaneous_expense',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
