# Generated by Django 4.2.2 on 2023-10-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_financialstatement_miscellaneous_expense_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monthlyincome',
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='current_debt',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='disposable_income',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='risk_tolerance',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='time_to_pay',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
    ]
