# Generated by Django 4.1.7 on 2023-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_financialstatement_miscellaneous_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialstatement',
            name='disposable_income',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
    ]
