# Generated by Django 4.1.7 on 2023-10-08 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_financialstatement_disposable_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='monthlyincome',
        ),
    ]
