# Generated by Django 4.1.7 on 2023-10-08 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_user_monthlyincome'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='current_debt',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='risk_tolerance',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='time_to_pay',
            field=models.DecimalField(decimal_places=1, max_digits=3, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='wick', max_length=255),
            preserve_default=False,
        ),
    ]
